### ISSUE TITLE
API KEY ISSUE

### ISSUE THREAD

**Issue by ghost** [AdamBrodin/th2103-g07#48]
# API KEYS
TRAFIKVERKET_API_KEY = API-KEY-HERE
STRIPE_PRIVATE_KEY = API-KEY-HERE

How do I get these keys to run this project in my local environment or in production?
Please answer as soon as possible in English !!!!!!!!!!!!
@lemuringen  @Kristianjimmefors @adambrodin @mzarabi @Spuute

**Comment by adambrodin** [comment]
Hi @yahyanoor007! 

This project was made for educational purposes/for a school course so that's why some parts might be a little confusing.

The `TRAFIKVERKET_API_KEY` comes from a public Swedish train data [API](https://api.trafikinfo.trafikverket.se/API) but it's not neccessary in order to run the application and since that API is in Swedish it might be difficult to understand however you can skip it entirely and add your own data instead.

To get a `STRIPE_PRIVATE_KEY` you'll need to create a **Stripe account & application** and use that key, you can read more about that [here](https://support.stripe.com/topics/getting-started).

**Comment by ghost** [comment]
Thank you so much. @adambrodin
